#- alias: Turn on tv when there is movement in the livingroom
#  trigger:
#    platform: state
#    entity_id: binary_sensor.motion_sensor_158d0001ddab4e
#    to: 'on'
#  action:
#    service: script.turn_on_tv


- alias: Despertador
  trigger:
    platform: template
    value_template: '{{ states.sensor.time.state == states.input_select.alarma_cuarto.state }}'
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
#  condition: state
#    entity_id: input_boolean.despcuarto
#    state: 'on'
#  - condition: state
#    entity_id: group.familia
#    state: 'home'
  action:
    service: scene.turn_on
    entity_id: scene.bathroom

- alias: Turn on bathroom light when there is movement in the bathroom
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0001ddcd68
    to: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: switch.bathroom_light

- alias: Turn off lily light 5 minutes after last movement
  trigger:                                                    
    platform: state                                           
    entity_id: binary_sensor.motion_sensor_158d000223670b   
    to: 'off'                                            
    for:                                                 
      minutes: 5                                         
  action:       
    service: homeassistant.turn_off
    entity_id: switch.lily_light 

- alias: Turn off lily small light 5 minutes after last movement
  trigger:                                                    
    platform: state                                           
    entity_id: binary_sensor.motion_sensor_158d000223670b   
    to: 'off'                                            
    for:                                                 
      minutes: 5                                         
  action:       
    service: homeassistant.turn_off
    entity_id: switch.lily_small_light 

- alias: Turn off Main bedroom light 5 minutes after last movement
  trigger:                                                    
    platform: state                                           
    entity_id: binary_sensor.motion_sensor_158d000224fc2a
    to: 'off'                                            
    for:                                                 
      minutes: 5                                         
  action:       
    service: homeassistant.turn_off
    entity_id: switch.room_light

- alias: Turn off table light light 10 minutes after last movement
  trigger:                                                        
    platform: state                                               
    entity_id: binary_sensor.motion_sensor_158d0001ddab4e 
    to: 'off'                                                     
    for:                                                          
      minutes: 10                                                  
  action:                                                         
    service: homeassistant.turn_off                                
    entity_id: switch.table_switch

- alias: Turn off sofa light light 10 minutes after last movement
  trigger:                                                        
    platform: state                                               
    entity_id: binary_sensor.motion_sensor_158d0001ddab4e 
    to: 'off'                                                     
    for:                                                          
      minutes: 10                                                  
  action:                                                         
    service: homeassistant.turn_off                                
    entity_id: switch.sofa_switch

- alias: Turn off bathroom light 5 minutes after last movement
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0001ddcd68
    to: 'off'
    for:
      minutes: 5
  action:
    service: homeassistant.turn_off
    entity_id: switch.bathroom_light

- alias: Turn on small bathroom light when there is movement in the bathroom
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0002236c2d
    to: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: switch.small_bathroom_light

- alias: Turn off small bathroom light 5 minutes after last movement
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0002236c2d
    to: 'off'
    for:
      minutes: 5
  action:
    service: homeassistant.turn_off
    entity_id: switch.small_bathroom_light

- alias: Turn on kitchen light when there is movement
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0001c21886
    to: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: switch.kitchen_light

- alias: Turn off kitchen light 10 minutes after last movement
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0001c21886
    to: 'off'
    for:
      minutes: 10
  action:
    service: homeassistant.turn_off
    entity_id: switch.kitchen_light

- alias: Turn off father light 5 minutes after last movement
  trigger:                                          
    platform: state                                 
    entity_id: binary_sensor.motion_sensor_158d00022347c7
    to: 'off'                                       
    for:                                                                                       
      minutes: 5                                   
  action:                                           
    service: homeassistant.turn_off                 
    entity_id: switch.father_light 

- alias: Turn off all lights, air conditioner and TV
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0001abcecd
      click_type: long_click_press
  action:
    service: script.turn_off_everything

- alias: Turn on bedroom light
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0001abcecd
      click_type: single
  action:
    service: homeassistant.turn_on
    data:
      entity_id: 
        - switch.room_light

- alias: Turn off bedroom light
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0001abcecd
      click_type: double
  action:
    service: homeassistant.turn_off
    data:
      entity_id: 
        - switch.room_light

- alias: Turn onoff lily light
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.wall_switch_158d000183ae29
      click_type: single
  action:
    service: script.lily_light

- alias: Turn onoff father light
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.wall_switch_158d000183ad36
      click_type: single
  action:
    service: script.father_light

- alias: Set TV Channel
  trigger:
    platform: state
    entity_id: input_select.tv_channels
  action:
    service: script.turn_on
    data_template:
      entity_id: >
        {% if trigger.to_state.state == "axn" %}
          script.axn
        {% elif trigger.to_state.state == "be_mad" %}
          script.be_mad
        {% elif trigger.to_state.state == "discovery" %}
          script.discovery
        {% elif trigger.to_state.state == 'disney_junior' %}
          script.disney_junior
        {% elif trigger.to_state.state == 'divinity' %}
          script.divinity
        {% elif trigger.to_state.state == 'dmax' %}
          script.dmax
        {% elif trigger.to_state.state == 'fox' %}
          script.fox
        {% elif trigger.to_state.state == 'fox_live' %}
          script.fox_live
        {% elif trigger.to_state.state == 'history_channel' %}
          script.history_channel
        {% elif trigger.to_state.state == 'hollywood' %}
          script.hollywood
        {% elif trigger.to_state.state == 'home' %}
          script.home
        {% elif trigger.to_state.state == 'mega' %}
          script.mega
        {% elif trigger.to_state.state == 'mtv_hits' %}
          script.mtv_hits
        {% elif trigger.to_state.state == "mtv_live" %}
          script.mtv_live
        {% elif trigger.to_state.state == "mtv_music" %}
          script.mtv_music
        {% elif trigger.to_state.state == 'mtv_spain' %}
          script.mtv_spain
        {% elif trigger.to_state.state == 'national_geographic' %}
          script.national_geographic
        {% elif trigger.to_state.state == 'neox' %}
          script.neox
        {% elif trigger.to_state.state == "nova" %}
          script.nova
        {% elif trigger.to_state.state == 'odyssey' %}
          script.odyssey
        {% elif trigger.to_state.state == 'syfy' %}
          script.syfy
        {% elif trigger.to_state.state == 'tnt' %}
          script.tnt
        {% elif trigger.to_state.state == 'travel' %}
          script.travel
        {% elif trigger.to_state.state == 'tv_five' %}
          script.tv_five
        {% elif trigger.to_state.state == 'tv_four' %}
          script.tv_four
        {% elif trigger.to_state.state == 'tv_one' %}
          script.tv_one
        {% elif trigger.to_state.state == 'tv_six' %}
          script.tv_six
        {% elif trigger.to_state.state == 'tv_three' %}
          script.tv_three
        {% elif trigger.to_state.state == 'tv_two' %}
          script.tv_two
        {% elif trigger.to_state.state == 'wild' %}
          script.wild
        {% endif %}
#    service: input_select.select_option
#    data:
#      entity_id: input_select.tv_channels
#      option: "none"

#- alias: welcome home
#  trigger:
#    platform: state
#    entity_id: device_tracker.ecd09f1f74fc, device_tracker.30074d88ac33
#    from: 'not_home'
#    to: 'home'
#    # If given, will trigger when state has been the to state for X time.
##    for:
##      hours: 1
##      minutes: 10
##      seconds: 5
#  action:                                                     
#    service: homeassistant.turn_on
#    data:                                                     
#      entity_id:                                              
#        - switch.air_conditioner_heat_mode
